#!/usr/bin/env python3

import rospy

if __name__ == "__main__":
    try:
        rospy.init_node("py_node")
        rospy.loginfo("Starting py_node")

        rospy.spin()

    except rospy.ROSInterruptException:
        rospy.logerr("Exception encountered")
    finally:
        rospy.loginfo("Stopping admin")
